### ISSUE TITLE
Code refactoring

### ISSUE THREAD

**Issue by epifanio** [steingod/solrindexing#15]
Will be good to start to split the several methods into separate files so to keep the code organized in modules. A start could be to isolate the code to generate thumbnails from the indexing.
Also, methods that are used from a different repository could be stored in a separate module and used as a dependency (this should address the issue  https://github.com/steingod/solrindexing/issues/11 ) 
Potentially we could build a separate module with utility functions which we can try to keep as more generic as possible, make them installable into the Python libraries and make them available on PyPI.

**Comment by magnarem** [comment]
This is done in the new solr-indexer: https://github.com/metno/solr-indexer
