### ISSUE TITLE
Fix bulk indexing

### ISSUE THREAD

**Issue by steingod** [steingod/solrindexing#47]
Bulk indexing works fine unless WMS thumbnails are to be added as these require too much memory. Either the bulk indexer needs to be updated, but better, @magnarem is this handled in the multi-threaded version you are working on? If so, then I suggest to postpone this until you have that version merged.

**Comment by magnarem** [comment]
We now have a working multi-threaded and multi-process bulkindexer in https://github.com/metno/solr-indexer with WMS thumbnail creation support.
