### ISSUE TITLE
skipping opendap reading if featureType is not present

### ISSUE THREAD

**Issue by ferrighi** [steingod/solrindexing#52]
Would it make sense to add an argument (like -f) to skip the get_feature_type in case we know there isn't such attribute? 
then if we need to index thousands of records without featureType we could avoid opening the file for no reason.

**Comment by steingod** [comment]
Yes, had so earlier and then removed, can reimplement.

On Thu, 2023-09-07 at 06:39 -0700, Lara Ferrighi wrote:
> Would it make sense to add an argument (like -f) to skip the
> get_feature_type in case we know there isn't such attribute?
> then if we need to index thousands of records without featureType we
> could avoid opening the file for no reason.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this
> thread.Message ID: ***@***.***>

-- 
Dr. Øystein Godøy
Norwegian Meteorological Institute 
P.O.BOX 43, Blindern, N-0313 OSLO, Norway
Ph: (+47) 9802 4433

**Comment by steingod** [comment]
This is implemented. Closing.
