### ISSUE TITLE
Allow related_information to be indexed as multivalue

### ISSUE THREAD

**Issue by ferrighi** [steingod/solrindexing#54]
For now the related_information of the same type are not appended in a list, but they are overwritten. This prevents to index for example several "Scientific publication" type of resources. While for landing pages it would make sense to have only one value, for other types this is a shortcoming. 
Solr already support a multi_value field. We just need to make sure to populate resource and description in a consistent way, so the url list is matching the description list (i.e. indexing an empty string if description is not available). 

I can try to make a PR

**Comment by magnarem** [comment]
I think indexing a empty string will work. But it is possible to try. If it not works, we will have to use a string like "NA" or "Not applicable" or some default string. Ie. "scientific publication" "other documentation" etc.

**Comment by ferrighi** [comment]
@magnarem would it make it a problem on the portals to have multiple landing pages since it is a clickable single element? Would we need to change how METSIS parse the SolR value? I could make an exception to have a single element for landing pages eventually. Alternatively, we can have METSIS only use one.

**Comment by ferrighi** [comment]
We have also feedback that we do not have experience of harvesting multiple landing pages.

**Comment by magnarem** [comment]
Yes it is no problem to have multiple landing pages also. So for metsis-search/drupal, we will just pick the first one for the link, and in the extended metadata, we can list all links. So then the "MAIN" landingpage have to be the first one added to the list while indexing.

Also, when we are happy with this change, we should also change the solr-indexer at github.com/metno/solr-indexer
